# Group AdGroups/ISULists
ISULists can be accessed and updated here.

## ISULists Collection [/adGroups/:id/isuLists/?include=includes]
Get all ISULists that are part of a AdGroup 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the AdGroup to perform action with. Has example value.

### Retrieve all ISULists for a AdGroup [GET]
+ Response 200 (application/json)

    + Body
            [
                { 
                data : {
                    modified_by: null
                    name: "My List 1"
                    url: "http://my.list.com/resource"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "ISUList"
                    version: 1
                    modifier: null
                    id: 1
                    }
                },
                {
                 data : {
                    modified_by: null
                    name: "My List 2"
                    url: "http://my.list.com/resource"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "ISUList"
                    version: 1
                    modifier: null
                    id: 2
                    }
                }
            ]

## ISUList [/adGroups/:id/isuLists/:subid/?include=includes]
Get a ISULists that is associated with a AdGroup 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the AdGroup to perform action with. Has example value.
    + subid (required, number, `1`) ... Numeric `id` of the ISUList to perform action with. Has example value.

### Retrieve a ISUList [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "My List 1"
                  url: "http://my.list.com/resource"
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "ISUList"
                  version: 1
                  modifier: null
                  id: 1
                }
            }

### Attach A ISUList to a AdGroup [POST]


+ Request (application/json)

        {
        }

+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "My List 1"
                  url: "http://my.list.com/resource"
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "ISUList"
                  version: 1
                  modifier: null
                  id: 1
                }
            }

### Remove a ISUList from a AdGroup [DELETE]

+ Response 200
