# Group AdGroups/GeoGroups
GeoGroups can be accessed and updated here.

## GeoGroups Collection [/adGroups/:id/geoGroups/?include=includes]
Get all GeoGroups that are part of a AdGroup 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the AdGroup to perform action with. Has example value.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the GeoGroup. Options are: `modifier`, `provinces`, `cities`, `countries`, or `all`

### Retrieve all GeoGroups for a AdGroup [GET]
+ Response 200 (application/json)

    + Body
            [
                {
                    data: {
                      modified_by: null
                      name: "USA + UK"
                      demandAccount_id: 4
                      created_at: "2014-03-25T21:30:42+00:00"
                      updated_at: "2014-03-25T21:30:42+00:00"
                      class: "GeoGroup"
                      version: 1
                      modifier: null
                      id: 1
                    }
                },
                    data: {
                      modified_by: null
                      name: "APAC"
                      demandAccount_id: 4
                      created_at: "2014-03-25T21:30:42+00:00"
                      updated_at: "2014-03-25T21:30:42+00:00"
                      class: "GeoGroup"
                      version: 1
                      modifier: null
                      id: 2
                    }
            ]

## GeoGroup [/adGroups/:id/geoGroup/:subid/?include=includes]
Get a GeoGroups that is associated with a AdGroup 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the AdGroup to perform action with. Has example value.
    + subid (required, number, `1`) ... Numeric `id` of the GeoGroup to perform action with. Has example value.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the GeoGroup. Options are: `modifier`, `provinces`, `cities`, `countries`, or `all`

### Retrieve a GeoGroup [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "USA + UK"
                  demandAccount_id: :id
                  cities: { { } }
                  provinces: { { } }
                  countries: { { } }
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "GeoGroup"
                  version: 1
                  modifier: null
                  id: :subid
                }
            }

### Attach A GeoGroup to a AdGroup [POST]


+ Request (application/json)

        {
        }

+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "USA + UK"
                  demandAccount_id: :id
                  cities: { { } }
                  provinces: { { } }
                  countries: { { } }
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "GeoGroup"
                  version: 1
                  modifier: null
                  id: :subid
                }
            }

### Remove a GeoGroup from a AdGroup [DELETE]

+ Response 200
