# Group AdGroups/Rating
The Rating of a AdGroup can be accessed and updated here.

## Rating [/adGroups/:id/rating/?include=includes]
Get the Rating that the AdGroup is using 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the AdGroup to perform action with. Has example value.

### Retrieve the Rating for a AdGroup [GET]
+ Response 200 (application/json)

    + Body
            { 
            data : {
                modified_by: null
                name: "PG"
                minimum_age: 10
                created_at: "2014-03-25T21:30:42+00:00"
                updated_at: "2014-03-25T21:30:42+00:00"
                class: "Rating"
                version: 1
                modifier: null
                id: 1
                }
            }

## Rating [/adGroups/:id/rating/:subid/?include=includes]
Get the Rating that the adGroup is using by ID 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the AdGroup to perform action with. Has example value.
    + subid (required, number, `1`) ... Numeric `id` of the Rating to perform action with. Has example value.

### Retrieve a Rating by ID [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "PG"
                  minimum_age: 10
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "Rating"
                  version: 1
                  modifier: null
                  id: 1
                }
            }

### Change the Rating that a AdGroup uses [POST]


+ Request (application/json)

        {
        }

+ Response 200 (application/json)

    + Body
            {
                data: {
                  modified_by: null
                  name: "PG"
                  minimum_age: 10
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "Rating"
                  version: 1
                  modifier: null
                  id: 1
                }
            }

### Remove a Rating from a AdGroup [DELETE]

+ Response 200
