# Group Auth
## Logging in [/login]

### Logging in! [POST]
+ Request (application/json)

    
        {
            username: "vungle"
            password: "my password"

        }

+ Response 200 (application/json)

        {
            username: "vungle"
            first_name: "I'm a"
            last_name: "Computer"
            modified_by: null
            created_at: "2014-03-12T15:48:36+00:00"
            updated_at: "2014-03-12T15:48:36+00:00"
            class: "User"
            version: 1
            is_admin: true
            id: 4
        }
        
## Logging out [/logout]

### Logging out! [GET]
+ Response 200
