# Group BidStrategies
BidStrategies can be accessed here, and admins can update / add new ones.

## BidStrategies Collection [/bidStrategies?limit=limit]
+ Parameters
    + limit (optional, number, `1`) ... Numerical `limit` to apply to how many records are returned.

### Retrieve all BidStrategies [GET]
+ Response 200 (application/json)

    + Body
            {
                data : [ 
                    {
                    modified_by: null
                    name: "CPI"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "BidStrategy"
                    version: 1
                    modifier: null
                    id: 1
                    },
                    {
                    modified_by: null
                    name: "CPC"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "BidStrategy"
                    version: 1
                    modifier: null
                    id: 2
                    }
                ]
            }
            
## BidStrategy [/bidStrategies/id]
Get a single BidStrategy object 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the BidStrategy to perform action with.

### Retrieve a BidStrategy [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "CPI"
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "BidStrategy"
                  version: 1
                  modifier: null
                  id: 1
                }
            }
