# Group Campaigns/BidStrategys
The BidStrategy of a Campaign can be accessed and updated here.

## BidStrategy [/campaigns/:id/bidStrategy/?include=includes]
Get the BidStrategy that the Campaign is using 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Campaign to perform action with. Has example value.

### Retrieve all BidStrategys for a Campaign [GET]
+ Response 200 (application/json)

    + Body
            [
                { 
                data : {
                    modified_by: null
                    name: "CPI"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "BidStrategy"
                    version: 1
                    modifier: null
                    id: 1
                    }
                },
                {
                 data : {
                    modified_by: null
                    name: "CPM"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "BidStrategy"
                    version: 1
                    modifier: null
                    id: 2
                    }
                }
            ]

## BidStrategy [/campaigns/:id/bidStrategy/:subid/?include=includes]
Get the BidStrategy that the campaign is using by ID 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Campaign to perform action with. Has example value.
    + subid (required, number, `1`) ... Numeric `id` of the BidStrategy to perform action with. Has example value.

### Retrieve a BidStrategy by ID [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "CPI"
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "BidStrategy"
                  version: 1
                  modifier: null
                  id: 1
                }
            }

### Change the BidStrategy that a Campaign uses [POST]


+ Request (application/json)

        {
        }

+ Response 200 (application/json)

        {
        }

### Remove a BidStrategy from a Campaign [DELETE]

+ Response 200
