## Status [/campaigns/:id/status/?include=includes]
Get the Status that the Campaign is using 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Campaign to perform action with. Has example value.

### Retrieve the Status for a Campaign [GET]
+ Response 200 (application/json)

    + Body
            { 
            data : {
                modified_by: null
                name: "Active"
                created_at: "2014-03-25T21:30:42+00:00"
                updated_at: "2014-03-25T21:30:42+00:00"
                class: "Status"
                version: 1
                modifier: null
                id: 1
                }
            }

## Status [/campaigns/:id/status/:subid/?include=includes]
Get the Status that the campaign is using by ID 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Campaign to perform action with. Has example value.
    + subid (required, number, `1`) ... Numeric `id` of the Status to perform action with. Has example value.

### Retrieve a Status by ID [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "Active"
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "Status"
                  version: 1
                  modifier: null
                  id: 1
                }
            }

### Change the Status that a Campaign uses [POST]


+ Request (application/json)

        {
        }

+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "Active"
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "Status"
                  version: 1
                  modifier: null
                  id: 1
                }
            }

### Remove a Status from a Campaign [DELETE]

+ Response 200
