# Group Campaigns/Ratings
The Rating of a Campaign can be accessed and updated here.

## Rating [/campaigns/:id/rating/?include=includes]
Get the Rating that the Campaign is using 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Campaign to perform action with. Has example value.

### Retrieve all Ratings for a Campaign [GET]
+ Response 200 (application/json)

    + Body
            [
                { 
                data : {
                    modified_by: null
                    name: "PG"
                    minimum_age: 10
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "Rating"
                    version: 1
                    modifier: null
                    id: 1
                    }
                },
                {
                 data : {
                    modified_by: null
                    name: "G"
                    minimum_age: 5
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "Rating"
                    version: 1
                    modifier: null
                    id: 2
                    }
                }
            ]

## Rating [/campaigns/:id/rating/:subid/?include=includes]
Get the Rating that the campaign is using by ID 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Campaign to perform action with. Has example value.
    + subid (required, number, `1`) ... Numeric `id` of the Rating to perform action with. Has example value.

### Retrieve a Rating by ID [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "PG"
                  minimum_age: 10
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "Rating"
                  version: 1
                  modifier: null
                  id: 1
                }
            }

### Change the Rating that a Campaign uses [POST]


+ Request (application/json)

        {
        }

+ Response 200 (application/json)

        {
        }

### Remove a Rating from a Campaign [DELETE]

+ Response 200
