# Group Categories
Categories can be accessed here, and admins can update / add new ones. 
Categories can have sub-categories, they can be accessed via `categories` on a category object. There is currently only 2 levels of categories allowed. 
`parent` is either null or the category that the current category is a sub-category of.


## Categories Collection [/categories?include=includes&limit=limit]
+ Parameters
    + limit (optional, number, `1`) ... Numerical `limit` to apply to how many records are returned.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `modifier`, `categories`,`parent` or `all`

### Retrieve all Categories [GET]
+ Response 200 (application/json)

    + Body
            {
                data : [ 
                    {
                    modified_by: null
                    name: "Games"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "Category"
                    iab_id: 5
                    parent_id: null
                    version: 1
                    modifier: null
                    id: 1
                    },
                    {
                    modified_by: null
                    name: "Newsstand"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "Category"
                    iab_id: null 
                    parent_id: 1
                    version: 1
                    modifier: null
                    id: 2
                    }
                ]
            }
            


## Categories Create [/categories]
### Create a Category [POST]
+ Request (application/json)

    
        {
            data : {
                name: "Adventure"
                iab_id: 5
            }

        }

        

+ Response 200 (application/json)

        { 
          data: {
            modified_by: null
            name: "Adventure"
            created_at: "2014-03-25T21:30:42+00:00"
            updated_at: "2014-03-25T21:30:42+00:00"
            class: "Category"
            iab_id: 5 
            parent_id: null
            version: 1
            modifier: null
            id: 1
          }
        }

## Category [/categories/id?include=includes]
Get a single Category object 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Category to perform action with. Has example value.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `modifier`, `categories`, `parent`, or `all`

### Retrieve a Category [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "Newsstand"
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "Category"
                  iab_id: 5 
                  parent_id: null
                  version: 1
                  modifier: null
                  id: 1
                  categories: {{}}
                }
            }
            
### Update A Category [PATCH]

+ Request (application/json)

        {
            data: {
                name: "New Category"
            }
        }
+ Response 200 (application/json)

        {
            data : {
              modified_by: null
              name: "New Category"
              created_at: "2014-03-25T21:30:42+00:00"
              updated_at: "2014-03-25T21:30:42+00:00"
              class: "Category"
              version: 2
              modifier: null
              id: 1
            }
        }   

### Remove a Category [DELETE]

+ Response 200




