# Group Company 
Companies! 
This is an Admin-Only endpoint except for GET.

## Companies Collection [/companies?include=includes&limit=limit]
+ Parameters
    + limit (optional, number, `1`) ... Numerical `limit` to apply to how many records are returned.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `modifier`, or `all`

### Retrieve all Companies [GET]

+ Response 200 (application/json)

    + Body

        [
            {
                modified_by: null
                name: "Company 1"
                created_at: "2014-03-13T19:58:38+00:00"
                updated_at: "2014-03-13T19:58:38+00:00"
                class: "Company"
                version: 1
                modifier: null
                id: 1
            },
            {
                modified_by: null
                name: "Company 2"
                created_at: "2014-03-13T19:58:38+00:00"
                updated_at: "2014-03-13T19:58:38+00:00"
                class: "Company"
                version: 1
                modifier: null
                id: 2
            }
        ]  

## Companies Create [/companies]
### Create a Company [POST]
+ Request (application/json)

    
        {
            name: "vungle"
        }

        

+ Response 200 (application/json)

        {
            modified_by: null
            name: "vungle"
            created_at: "2014-03-13T19:58:38+00:00"
            updated_at: "2014-03-13T19:58:38+00:00"
            class: "Company"
            version: 1
            modifier: null
            id: 2
        }

## Company [/companies/id?include=includes]
Get a single Company object 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `modifier`, or `all`

### Retrieve a single Company [GET]
+ Response 200 (application/json)

    + Body

            {
                modified_by: null
                name: "vungle"
                created_at: "2014-03-13T19:58:38+00:00"
                updated_at: "2014-03-13T19:58:38+00:00"
                class: "Company"
                version: 1
                modifier: null
                id: 2
            }
            
### Update A User [PATCH]

+ Request (application/json)

        {
            name: "Vungly Vungle"
        }
+ Response 200 (application/json)

        {
            name: "Vungly Vungle"
            modified_by: 1
            created_at: "2014-03-12T16:29:48+00:00"
            updated_at: "2014-03-12T16:33:48+00:00"
            class: "Company"
            version: 2
            id: 1
        }   

##  Delete a Company [/companies/id]
### Remove a Company [DELETE]
+ Response 200




