# Group DemandAccounts/SiteIDLists
SiteIDLists for a DemandAccount can be accessed and created here. 

## SiteIDList [/demandAccounts/:id/siteIDLists/?include=includes]
Get all SiteIDLists that are associated with a DemandAccount 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the DemandAccount to perform action with. Has example value.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `adUnits`, `modifier`, `demandAcccount`,  or `all` 

### Retrieve all SiteIDLists [GET]
+ Response 200 (application/json)

    + Body

            [
                {
                    data: {
                      modified_by: null
                      name: "SiteIDList1"
                      url: "http://url.com"
                      created_at: "2014-03-25T21:30:42+00:00"
                      updated_at: "2014-03-25T21:30:42+00:00"
                      class: "SiteIDList"
                      version: 1
                      modifier: null
                      id: 1
                    }
                },
                {
                    data: {
                      modified_by: null
                      name: "SiteIDList2"
                      url: "http://url.com"
                      created_at: "2014-03-25T21:30:42+00:00"
                      updated_at: "2014-03-25T21:30:42+00:00"
                      class: "SiteIDList"
                      version: 1
                      modifier: null
                      id: 2
                    }
                }
            ]

### Create A SiteIDList [POST]


+ Request (application/json)

        {
            data: {
               name: "Anglophones" 
               url: "http://url.com"
            }
        }

+ Response 200 (application/json)

        {
            data: {
              modified_by: null
              name: "Anglophones"
              url: "http://url.com"
              created_at: "2014-03-25T21:30:42+00:00"
              updated_at: "2014-03-25T21:30:42+00:00"
              class: "SiteIDList"
              version: 1
              modifier: null
              id: 10
            }
        }
