## Geogroup City Collection [/geoGroups/:id/cities?include=includes&limit=limit]
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the parent GeoGroup to perform action with.
    + limit (optional, number, `1`) ... Numerical `limit` to apply to how many records are returned.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `modifier`, `province`, or `all`

### Retrieve all Cities that are part of a Geogroup [GET]
+ Response 200 (application/json)

    + Body
            {
                data : [ 
                    {
                    modified_by: null
                    name: "New York City"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "City"
                    province_id: 8
                    version: 1
                    modifier: null
                    id: 1
                    },
                    {
                    modified_by: null
                    name: "Albaquerque"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "City"
                    province_id: 1
                    version: 1
                    modifier: null
                    id: 2
                    }
                ]
            }
            
## City [/geoGroups/:id/cities/:subid?include=includes]
Get a single City on a geoGroup object 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the parent GeoGroup to perform action with.
    + subid (required, number, `2`) ... Numeric `id` of the City to perform action with. Has example value.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `modifier`, `province`, or `all`

### Retrieve a City [GET]
+ Response 200 (application/json)

    + Body

            {
               data : {
                  modified_by: null
                  name: "Albaquerque"
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "City"
                  province_id: 1
                  version: 1
                  modifier: null
                  id: 2
                }
            }
            
### Add a City to a GeoGroup [POST]

+ Response 200 (application/json)

        {
           data : {
              modified_by: null
              name: "Albaquerque"
              created_at: "2014-03-25T21:30:42+00:00"
              updated_at: "2014-03-25T21:30:42+00:00"
              class: "City"
              province_id: 1
              version: 1
              modifier: null
              id: 2
            }
        }   

### Remove a City from a GeoGroup [DELETE]

+ Response 200




