## Platform PlatformVersions Collection [/platforms/:id/platformVersions?limit=limit]
+ Parameters
    + limit (optional, number, `1`) ... Numerical `limit` to apply to how many records are returned.

### Retrieve all PlatformVersions for a Platform [GET]
+ Response 200 (application/json)

    + Body
            {
                data : [ 
                    {
                    modified_by: null
                    platform_version: 7
                    platform_id: :id
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "PlatformVersion"
                    version: 1
                    modifier: null
                    id: 1
                    },
                    {
                    modified_by: null
                    platform_version: 2.2
                    platform_id: :id
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "PlatformVersion"
                    version: 1
                    modifier: null
                    id: 2
                    }
                ]
            }

## Create a PlatformVersion for a Platform [/platforms/:id/platformVersions/]
Create a single PlatformVersion object 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the platform to perform action with. Has example value.

+ Request (application/json)

        {
            data: {
               platform_version : 3.14
            }
        }

+ Response 200 (application/json)

        {
            data: {
              modified_by: null
              platform_version: 3.14 
              platform_id: :id
              created_at: "2014-03-25T21:30:42+00:00"
              updated_at: "2014-03-25T21:30:42+00:00"
              class: "PlatformVersion"
              version: 1
              modifier: null
              id: 2
            }
        }


            
## Get a specific PlatformVersion for a Platform [/platforms/:id/platformVersions/:subid/]
Get a single PlatformVersion object 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the platform to perform action with. Has example value.
    + subid (required, number, `1`) ... Numeric `id` of the platformVersion to perform action with. Has example value.

### Retrieve a specific PlatformVersion for a specific Platform [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  platform_version: 2.2 
                  platform_id: 2
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "PlatformVersion"
                  version: 1
                  modifier: null
                  id: 2
                }
            }
