## Provinces/Cities Collection [/provinces/:id/cities?include=includes&limit=limit]
Cities that are a part of a specific Province can be accessed here.
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Province to perform action with. Has example value.
    + limit (optional, number, `1`) ... Numerical `limit` to apply to how many records are returned.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `modifier` or `all`

### Retrieve all Cities that are part of a Country [GET]
+ Response 200 (application/json)

    + Body
            {
                data : [ 
                    {
                    modified_by: null
                    name: "New York City"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "City"
                    province_id: :id
                    version: 1
                    modifier: null
                    id: 1
                    },
                    {
                    modified_by: null
                    name: "Albaquerque"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "City"
                    province_id: :id
                    version: 1
                    modifier: null
                    id: 2
                    }
                ]
            }
            
## City  [/provinces/:id/cities/:subid?include=includes]
Get a single City object 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Province to perform action with. Has example value.
    + subid (required, number, `1`) ... Numeric `id` of the City to perform action with. Has example value.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `modifier` or `all`

### Retrieve a specific City under a Province [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "Albaquerque"
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "City"
                  province_id: :id 
                  version: 1
                  modifier: null
                  id: :subid
                }
            }
