# Group Statuses
Statuses can be accessed here, and admins can update / add new ones.

## Statuses Collection [/statuses?limit=limit]
+ Parameters
    + limit (optional, number, `1`) ... Numerical `limit` to apply to how many records are returned.

### Retrieve all Statuses [GET]
+ Response 200 (application/json)

    + Body
            [
                { 
                data : {
                    modified_by: null
                    name: "Active"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "Status"
                    version: 1
                    modifier: null
                    id: 1
                    }
                },
                {
                 data : {
                    modified_by: null
                    name: "Paused"
                    created_at: "2014-03-25T21:30:42+00:00"
                    updated_at: "2014-03-25T21:30:42+00:00"
                    class: "Status"
                    version: 1
                    modifier: null
                    id: 2
                    }
                }
            ]
            
## Status [/statuses/id]
Get a single Status object 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Status [GET]
+ Response 200 (application/json)

    + Body

            {
                data: {
                  modified_by: null
                  name: "psuedo-archived"
                  created_at: "2014-03-25T21:30:42+00:00"
                  updated_at: "2014-03-25T21:30:42+00:00"
                  class: "Status"
                  version: 1
                  modifier: null
                  id: 1
                }
            }
