## User's DemandAccounts Collection [/users/:id/demandAccounts?include=includes&limit=limit]
Allows you to get all demandAccounts associated with a user, and also to modify those relations.
+ Parameters
    + limit (optional, number, `1`) ... Numerical `limit` to apply to how many records are returned.
    + includes (optional, string, `'parent,videos'`) ... `includes` The relations that you want returned as part of the object. Options are `parent`,`agency`, `company`, `users`, `preRolls`, `postRolls`, `videos`, `adUnits`, `tpatGroups`, `geoGroups`, `campaigns, `children`, or `all`

### List all of a User's  DemandAccounts [GET]
+ Response 200 (application/json)


        {
            data : [ 
                    {
                    geo_targetting: true
                    mailing_address: "My Mailing Address"
                    updated_at: "2014-03-12T20:48:32+00:00"
                    is_agency: false
                    billing_phone: "3149355555"
                    mailing_email: "email@mailing.com"
                    modified_by: null
                    is_rtb: true
                    billing_email: "email@billing.com"
                    company_id: null
                    id: 1
                    parent_id: null
                    version: 1
                    billing_address: "My Billing Address"
                    category_restriction: false
                    agency_id: null
                    approved_credit: 1000
                    class: "DemandAccount"
                    age_restriction: true
                    mailing_phone: "2124843915"
                    name: "Vungle"
                    created_at: "2014-03-12T20:48:32+00:00"
                    spent_credit: 500
                    modifier: null
                    },
                    {
                    geo_targetting: false
                    mailing_address: "Need a value"
                    updated_at: "2014-03-12T20:48:32+00:00"
                    is_agency: false
                    billing_phone: "13123123"
                    mailing_email: "valid@asd.com"
                    modified_by: null
                    is_rtb: null
                    billing_email: "validated@validated.co.uk"
                    company_id: null
                    id: 2
                    parent_id: null
                    version: 1
                    billing_address: "bonk"
                    category_restriction: false
                    agency_id: null
                    approved_credit: null
                    class: "DemandAccount"
                    age_restriction: false
                    mailing_phone: "53453252"
                    name: "Vungle 2"
                    created_at: "2014-03-12T20:48:32+00:00"
                    spent_credit: null
                    modifier: null
                    }
            ]
            permissions: [
                    {
                    financial_write: true
                    user_id: :id
                    financial_read: true
                    read: true
                    created_at: "2014-03-27T17:50:30+00:00"
                    updated_at: "2014-03-27T17:50:30+00:00"
                    write: false
                    manager: true
                    version: 1
                    modified_by: null
                    modifier: null
                    reports_read: true
                    class: "UserDemandAccounts"
                    demandAccount_id: 1
                    },
                    {
                    financial_write: true
                    user_id: :id
                    financial_read: true
                    read: true
                    created_at: "2014-03-27T17:50:30+00:00"
                    updated_at: "2014-03-27T17:50:30+00:00"
                    write: false
                    manager: true
                    version: 1
                    modified_by: null
                    modifier: null
                    reports_read: true
                    class: "UserDemandAccounts"
                    demandAccount_id: 2
                    }
            ]
        }

## Demand Accounts Create [/users/:id/demandAccounts]
### Create a DemandAccount for a User [POST]
+ Request (application/json)

    
        {
            data: {
                geo_targetting: true
                mailing_address: "My Mailing Address"
                is_agency: false
                billing_phone: "3149355555"
                mailing_email: "email@mailing.com"
                is_rtb: true
                billing_email: "email@billing.com"
                id: 1
                billing_address: "My Billing Address"
                category_restriction: false
                age_restriction: true
                mailing_phone: "2124843915"
                name: "Vungle"
            }
            permissions: {
                financial_write: true
                financial_read: true
                write: true
                read: true
                manager: false
                reports_read: false
            }
        }
        
+ Response 200 (application/json)

        {
            data: {
                geo_targetting: true
                mailing_address: "My Mailing Address"
                updated_at: "2014-03-12T20:48:32+00:00"
                is_agency: false
                billing_phone: "3149355555"
                mailing_email: "email@mailing.com"
                modified_by: null
                is_rtb: true
                billing_email: "email@billing.com"
                company_id: null
                id: 1
                parent_id: null
                version: 1
                billing_address: "My Billing Address"
                category_restriction: false
                agency_id: null
                approved_credit: 1000
                class: "DemandAccount"
                age_restriction: true
                mailing_phone: "2124843915"
                name: "Vungle"
                created_at: "2014-03-12T20:48:32+00:00"
                spent_credit: 500
                modifier: null
            }
            permissions: {
                financial_write: true
                user_id: :id
                financial_read: true
                read: true
                created_at: "2014-03-27T17:50:30+00:00"
                updated_at: "2014-03-27T17:50:30+00:00"
                write: true 
                manager: false 
                version: 1
                modified_by: null
                modifier: null
                reports_read: false 
                class: "UserDemandAccounts"
                demandAccount_id: 1
            }
        }

## DemandAccounts [/users/:id/demandAccounts/:subid?include=includes&limit=limit]
Get a single DemandAccount and its permissions for a given user 

+ Parameters  
    + limit (optional, number, `1`) ... Numerical `limit` to apply to how many records are returned.
    + includes (optional, string, `'parent'`) ... `includes` The relations that you want returned as part of the object. Options are `parent`,`agency`, `company`, `users`, `preRolls`, `postRolls`, `    videos`, `adUnits`, `tpatGroups`, `geoGroups`, `campaigns, `children`, or `all`

### Get a single Demand Account for a user [GET]
+ Response 200 (application/json)
    
    + Body
    
            {
                data: {
                    geo_targetting: true
                    mailing_address: "My Mailing Address"
                    updated_at: "2014-03-12T20:48:32+00:00"
                    is_agency: false
                    billing_phone: "3149355555"
                    mailing_email: "email@mailing.com"
                    modified_by: null
                    is_rtb: true
                    billing_email: "email@billing.com"
                    company_id: null
                    id: 1
                    parent_id: null
                    version: 1
                    billing_address: "My Billing Address"
                    category_restriction: false
                    agency_id: null
                    approved_credit: 1000
                    class: "DemandAccount"
                    age_restriction: true
                    mailing_phone: "2124843915"
                    name: "Vungle"
                    created_at: "2014-03-12T20:48:32+00:00"
                    spent_credit: 500
                    modifier: null
                }
                permissions: {
                    financial_write: true
                    user_id: :id
                    financial_read: true
                    read: true
                    created_at: "2014-03-27T17:50:30+00:00"
                    updated_at: "2014-03-27T17:50:30+00:00"
                    write: true 
                    manager: false 
                    version: 1
                    modified_by: null
                    modifier: null
                    reports_read: false 
                    class: "UserDemandAccounts"
                    demandAccount_id: 1
                }
            }

### Modify the permissions between a User and a DemandAccount [POST]
+ Request (application/json)

        {
            permissions: {
                financial_read: false
            }
        }

+ Response 200 (application/json)
    
    + Body
    
            {
                data: {
                    geo_targetting: true
                    mailing_address: "My Mailing Address"
                    updated_at: "2014-03-12T20:48:32+00:00"
                    is_agency: false
                    billing_phone: "3149355555"
                    mailing_email: "email@mailing.com"
                    modified_by: null
                    is_rtb: true
                    billing_email: "email@billing.com"
                    company_id: null
                    id: 1
                    parent_id: null
                    version: 1
                    billing_address: "My Billing Address"
                    category_restriction: false
                    agency_id: null
                    approved_credit: 1000
                    class: "DemandAccount"
                    age_restriction: true
                    mailing_phone: "2124843915"
                    name: "Vungle"
                    created_at: "2014-03-12T20:48:32+00:00"
                    spent_credit: 500
                    modifier: null
                }
                permissions: {
                    financial_write: false
                    user_id: :id
                    financial_read: true
                    read: true
                    created_at: "2014-03-27T17:50:30+00:00"
                    updated_at: "2014-03-27T17:50:30+00:00"
                    write: true 
                    manager: false 
                    version: 1
                    modified_by: null
                    modifier: null
                    reports_read: false 
                    class: "UserDemandAccounts"
                    demandAccount_id: 1
                }
            }

##  Delete a DemandAccount from a user [/users/:id/demandAccounts/id]
### Remove a DemandAccount from a user [DELETE]
+ Response 200
