# Group Video
Videos! This is a somewhat complicated, First you post a create with a filename, then you upload the video to our S3 bucket with the format bucket:/id/filename 

## Videos Collection [/companies?include=includes&limit=limit]
+ Parameters
    + limit (optional, number, `1`) ... Numerical `limit` to apply to how many records are returned.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `modifier`, or `all`

### Retrieve all Videos [GET]

+ Response 200 (application/json)

    + Body

        [
            {
                modified_by: null
                name: "Video 1"
                created_at: "2014-03-13T19:58:38+00:00"
                updated_at: "2014-03-13T19:58:38+00:00"
                class: "Video"
                version: 1
                modifier: null
                id: 1
            },
            {
                modified_by: null
                name: "Video 2"
                created_at: "2014-03-13T19:58:38+00:00"
                updated_at: "2014-03-13T19:58:38+00:00"
                class: "Video"
                version: 1
                modifier: null
                id: 2
            }
        ]  

## Videos Create [/companies]
### Create a Video [POST]
+ Request (application/json)

    
        {
            name: "vungle"
        }

        

+ Response 200 (application/json)

        {
            modified_by: null
            name: "vungle"
            created_at: "2014-03-13T19:58:38+00:00"
            updated_at: "2014-03-13T19:58:38+00:00"
            class: "Video"
            version: 1
            modifier: null
            id: 2
        }

## Video [/companies/id?include=includes]
Get a single Video object 
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.
    + includes (optional, string, `'modifier'`) ... `includes` The relations that you want returned as part of the object. Options are: `modifier`, or `all`

### Retrieve a single Video [GET]
+ Response 200 (application/json)

    + Body

            {
                modified_by: null
                name: "vungle"
                created_at: "2014-03-13T19:58:38+00:00"
                updated_at: "2014-03-13T19:58:38+00:00"
                class: "Video"
                version: 1
                modifier: null
                id: 2
            }
            
### Update A Video [PATCH]

+ Request (application/json)

        {
            name: "Vungly Vungle"
        }
+ Response 200 (application/json)

        {
            name: "Vungly Vungle"
            modified_by: 1
            created_at: "2014-03-12T16:29:48+00:00"
            updated_at: "2014-03-12T16:33:48+00:00"
            class: "Video"
            version: 2
            id: 1
        }   

##  Delete a Video [/companies/id]
### Remove a Video [DELETE]
+ Response 200




